### ISSUE TITLE
[GUI] Design Goals & Progress Tracker

### ISSUE THREAD

**Issue by database64128** [shadowsocks/shadowsocks-windows#3125]
The main window consists of 5 tabs, selectable from the left navigation bar.
- Dashboard
    - [ ] Select which profile, group or server to connect
    - [ ] Speed graph
    - [ ] Logger output
    - [ ] Data usage
- Profiles
    - [ ] Select any server from any group to form a profile
    - [ ] Combine any backend inside each profile
    - [ ] Configure every detail of ss-rust and v2ray config
        - [ ] Inbounds and outbounds of v2ray
        - [ ] Use a tree view for other settings
- Servers
    - [ ] Manage SIP008 online config delivery
    - [ ] Manage groups of servers
    - [ ] Groups are shown as cards
        - [ ] Cards may use an expander.
        - [ ] Cards must show data usage if it's associated with an online config.
    - [ ] Select a group and a data grid shows servers in the group
    - [ ] The user may configure backend override settings for each group and server.
    - [ ] Import from ss:// links and export as ss:// links or QR codes.
- Routing
    - [ ] Add, delete, rename, duplicate presets
    - [ ] 2 built-in presets
        - [ ] Proxy everything
        - [ ] Direct connection for CN sites and IPs
    - [ ] Domain strategy
    - [ ] DNS
    - [ ] Routing rules
- Settings
    - [ ] App settings
        - [ ] Color theme
        - [ ] Default backend
        - [ ] Start on boot
        - [ ] Associate ss:// protocol
        - [ ] Check for updates
        - [ ] Logging
    - [ ] V2Ray settings
        - [ ] Binary path
        - [ ] Logging
        - [ ] Default socks port
        - [ ] Default http port
    - [ ] SS-rust settings
        - [ ] Binary path
        - [ ] Logging
        - [ ] Default UDP associations
        - [ ] Default UDP timeout
    - [ ] Built-in backend settings
        - [ ] Forward proxy

**Comment by database64128** [comment]
Moved to Shadowsocks-NET/Shadowsocks.NET#2
